### ISSUE TITLE
Not an issue, but are you 2010s Lego/RGM YouTuber coolfolder?

### ISSUE THREAD

**Issue by tungstenwire** [seth10/splatoon-maps-skill#1]
Hi! This may be completely out of the blue but I was somebody who watched coolfolder’s videos before, and has been looking for him on and off for a few weeks. I found your Twitter page via going to the Wayback Machine and typing coolfolder's archived video links into Twitter (most YouTube Collections videos were archived because they were linked on Twitter). I also found your Reddit and Steam because usernames were “coolfolder”. 

I'm in the Discord Domino and Machine community server and also previously messaged pikmintendo via Twitter-- if you see this message in your emails/GitHub, could you PM me (_tungstenwire) on Twitter? 

I want to ask, how are you, why you privated your channel, and if any other people have looked for you in the same way. Really sorry if all of this is intrusive, but your old videos are something inspiring that people want to see again.

Thank you, 
tungstenwire

**Comment by tungstenwire** [comment]
@seth10

**Comment by seth10** [comment]
Hi tungstenwire, I'm not sure who you're looking for but you have the wrong person, sorry.

**Comment by tungstenwire** [comment]
Sorry again if I troubled you in any way at all, and thanks for your time w/ replying.
